openapi: 3.0.0
info:
  description: This API provides access to Dexcom continuous glucose monitoring data
    for authorized users.
  title: Dexcom Developer API
  version: v3
servers:
- url: https://api.dexcom.com
security:
- BearerAuth: []
paths:
  /v3/users/self/dataRange:
    get:
      operationId: getDataRange
      parameters:
      - explode: true
        in: query
        name: lastSyncTime
        required: false
        schema:
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getDataRange_200_response"
          description: Data range retrieved successfully
  /v2/oauth2/login:
    get:
      operationId: userAuthorization
      parameters:
      - explode: true
        in: query
        name: client_id
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: redirect_uri
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: response_type
        required: true
        schema:
          enum:
          - code
          type: string
        style: form
      - explode: true
        in: query
        name: scope
        required: true
        schema:
          enum:
          - offline_access
          type: string
        style: form
      - explode: true
        in: query
        name: state
        required: false
        schema:
          type: string
        style: form
      responses:
        "302":
          description: Redirect to authorization code or access denied error
          headers:
            Location:
              explode: false
              schema:
                type: string
              style: simple
  /v2/oauth2/token:
    post:
      operationId: exchangeAuthorizationCode
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/exchangeAuthorizationCode_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/exchangeAuthorizationCode_200_response"
          description: Access token and refresh token returned
  /v3/users/self/alerts:
    get:
      operationId: getAlerts
      parameters:
      - explode: true
        in: query
        name: startDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      - explode: true
        in: query
        name: endDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlertRecord"
          description: Ok
  /v3/users/self/calibrations:
    get:
      operationId: getCalibrations
      parameters:
      - explode: true
        in: query
        name: startDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      - explode: true
        in: query
        name: endDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CalibrationRecord"
          description: Ok
  /v3/users/self/egvs:
    get:
      operationId: getEstimatedGlucoseValues
      parameters:
      - explode: true
        in: query
        name: startDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      - explode: true
        in: query
        name: endDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EGVRecord"
          description: Ok
  /v3/users/self/events:
    get:
      operationId: getEventsV3
      parameters:
      - explode: true
        in: query
        name: startDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      - explode: true
        in: query
        name: endDate
        required: true
        schema:
          $ref: "#/components/schemas/DateTime"
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/getEventsV3_200_response_inner"
                type: array
          description: Ok
  /v3/users/self/devices:
    get:
      operationId: getDevicesV3
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/getDevicesV3_200_response_inner"
                type: array
          description: Ok
components:
  schemas:
    DataRangeMoment:
      example:
        displayTime: 2000-01-23T04:56:07.000+00:00
        systemTime: 2000-01-23T04:56:07.000+00:00
      properties:
        systemTime:
          format: date-time
          title: systemTime
          type: string
        displayTime:
          format: date-time
          title: displayTime
          type: string
      required:
      - displayTime
      - systemTime
      title: DataRangeMoment
      type: object
    DateTime:
      format: date-time
      title: systemTime
      type: string
    AlertRecord:
      example:
        recordId: recordId
        displayTime: 2000-01-23T04:56:07.000+00:00
        displayDevice: displayDevice
        alertName: unknown
        transmitterGeneration: unknown
        alertState: unknown
        systemTime: 2000-01-23T04:56:07.000+00:00
        transmitterId: transmitterId
      properties:
        recordId:
          title: recordId
          type: string
        systemTime:
          format: date-time
          title: systemTime
          type: string
        displayTime:
          format: date-time
          title: systemTime
          type: string
        alertName:
          enum:
          - unknown
          - high
          - low
          - rise
          - fall
          - outOfRange
          - urgentLow
          - urgentLowSoon
          - noReadings
          - fixedLow
          title: alertName
          type: string
        alertState:
          enum:
          - unknown
          - inactive
          - activeSnoozed
          - activeAlarming
          title: alertState
          type: string
        displayDevice:
          title: displayDevice
          type: string
        transmitterGeneration:
          enum:
          - unknown
          - g4
          - g5
          - g6
          - g6+
          - dexcomPro
          - g7
          title: transmitterGeneration
          type: string
        transmitterId:
          title: transmitterId
          type: string
      title: AlertRecord
      type: object
    CalibrationRecord:
      example:
        recordId: recordId
        displayTime: 2000-01-23T04:56:07.000+00:00
        unit: unknown
        displayDevice: displayDevice
        transmitterGeneration: unknown
        systemTime: 2000-01-23T04:56:07.000+00:00
        value: 0
        transmitterId: transmitterId
        transmitterTicks: 6
      properties:
        recordId:
          title: recordId
          type: string
        unit:
          enum:
          - unknown
          - mg/dL
          - mmol/L
          title: unit
          type: string
        systemTime:
          format: date-time
          title: systemTime
          type: string
        displayTime:
          format: date-time
          title: systemTime
          type: string
        value:
          format: int32
          title: value
          type: integer
        displayDevice:
          title: displayDevice
          type: string
        transmitterId:
          title: transmitterId
          type: string
        transmitterTicks:
          format: int64
          title: transmitterTicks
          type: integer
        transmitterGeneration:
          enum:
          - unknown
          - g4
          - g5
          - g6
          - g6+
          - dexcomPro
          - g7
          title: transmitterGeneration
          type: string
      title: CalibrationRecord
      type: object
    EGVRecord:
      example:
        displayTime: 2000-01-23T04:56:07.000+00:00
        displayDevice: displayDevice
        trend: none
        trendRate: 1.4658129805029452
        rateUnit: unknown
        systemTime: 2000-01-23T04:56:07.000+00:00
        transmitterId: transmitterId
        transmitterTicks: 0
        recordId: recordId
        unit: unknown
        transmitterGeneration: unknown
        value: 6
        status: unknown
      properties:
        recordId:
          title: recordId
          type: string
        systemTime:
          format: date-time
          title: systemTime
          type: string
        displayTime:
          format: date-time
          title: systemTime
          type: string
        transmitterId:
          title: transmitterId
          type: string
        transmitterTicks:
          format: int64
          title: transmitterTicks
          type: integer
        value:
          format: int32
          title: value
          type: integer
        status:
          enum:
          - unknown
          - high
          - low
          - ok
          title: status
          type: string
        trend:
          enum:
          - none
          - unknown
          - doubleUp
          - singleUp
          - fortyFiveUp
          - flat
          - fortyFiveDown
          - singleDown
          - doubleDown
          - notComputable
          - rateOutOfRange
          title: trend
          type: string
        trendRate:
          format: double
          title: trendRate
          type: number
        unit:
          enum:
          - unknown
          - mg/dL
          - mmol/L
          title: unit
          type: string
        rateUnit:
          enum:
          - unknown
          - mg/dL/min
          - mmol/L/min
          title: rateUnit
          type: string
        displayDevice:
          title: displayDevice
          type: string
        transmitterGeneration:
          enum:
          - unknown
          - g4
          - g5
          - g6
          - g6+
          - dexcomPro
          - g7
          title: transmitterGeneration
          type: string
      title: EGVRecord
      type: object
    getDataRange_200_response_calibrations:
      example:
        start:
          displayTime: 2000-01-23T04:56:07.000+00:00
          systemTime: 2000-01-23T04:56:07.000+00:00
        end:
          displayTime: 2000-01-23T04:56:07.000+00:00
          systemTime: 2000-01-23T04:56:07.000+00:00
      properties:
        start:
          $ref: "#/components/schemas/DataRangeMoment"
        end:
          $ref: "#/components/schemas/DataRangeMoment"
      title: getDataRange_200_response_calibrations
      type: object
    getDataRange_200_response:
      example:
        egvs:
          start:
            displayTime: 2000-01-23T04:56:07.000+00:00
            systemTime: 2000-01-23T04:56:07.000+00:00
          end:
            displayTime: 2000-01-23T04:56:07.000+00:00
            systemTime: 2000-01-23T04:56:07.000+00:00
        calibrations:
          start:
            displayTime: 2000-01-23T04:56:07.000+00:00
            systemTime: 2000-01-23T04:56:07.000+00:00
          end:
            displayTime: 2000-01-23T04:56:07.000+00:00
            systemTime: 2000-01-23T04:56:07.000+00:00
        recordVersion: recordVersion
        recordType: recordType
        userId: userId
        events:
          start:
            displayTime: 2000-01-23T04:56:07.000+00:00
            systemTime: 2000-01-23T04:56:07.000+00:00
          end:
            displayTime: 2000-01-23T04:56:07.000+00:00
            systemTime: 2000-01-23T04:56:07.000+00:00
      properties:
        recordType:
          title: recordType
          type: string
        recordVersion:
          title: recordVersion
          type: string
        userId:
          title: userId
          type: string
        calibrations:
          $ref: "#/components/schemas/getDataRange_200_response_calibrations"
        egvs:
          $ref: "#/components/schemas/getDataRange_200_response_calibrations"
        events:
          $ref: "#/components/schemas/getDataRange_200_response_calibrations"
      title: getDataRange_200_response
      type: object
    exchangeAuthorizationCode_request:
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        code:
          type: string
        grant_type:
          enum:
          - authorization_code
          type: string
        redirect_uri:
          type: string
      required:
      - client_id
      - client_secret
      - code
      - grant_type
      - redirect_uri
      type: object
    exchangeAuthorizationCode_200_response:
      example:
        access_token: access_token
        refresh_token: refresh_token
        token_type: token_type
        expires_in: 0
      properties:
        access_token:
          title: access_token
          type: string
        expires_in:
          title: expires_in
          type: integer
        token_type:
          title: token_type
          type: string
        refresh_token:
          title: refresh_token
          type: string
      title: exchangeAuthorizationCode_200_response
      type: object
    getEventsV3_200_response_inner:
      example:
        eventId: eventId
        displayTime: 2000-01-23T04:56:07.000+00:00
        unit: ""
        displayDevice: ""
        transmitterGeneration: ""
        eventType: eventType
        systemTime: 2000-01-23T04:56:07.000+00:00
        value: ""
        transmitterId: ""
      properties:
        eventId:
          title: eventId
          type: string
        eventType:
          title: eventType
          type: string
        systemTime:
          format: date-time
          title: systemTime
          type: string
        displayTime:
          format: date-time
          title: systemTime
          type: string
        value:
          title: value
        unit:
          title: unit
        transmitterId:
          title: transmitterId
        transmitterGeneration:
          title: transmitterGeneration
        displayDevice:
          title: displayDevice
      title: getEventsV3_200_response_inner
      type: object
    getDevicesV3_200_response_inner:
      example:
        deviceType: deviceType
        deactivationDate: 2000-01-23T04:56:07.000+00:00
        displayDevice: ""
        transmitterGeneration: ""
        activationDate: 2000-01-23T04:56:07.000+00:00
        deviceId: deviceId
        transmitterId: ""
      properties:
        deviceId:
          title: deviceId
          type: string
        deviceType:
          title: deviceType
          type: string
        transmitterGeneration:
          title: transmitterGeneration
        transmitterId:
          title: transmitterId
        displayDevice:
          title: displayDevice
        activationDate:
          format: date-time
          title: systemTime
          type: string
        deactivationDate:
          format: date-time
          title: systemTime
          type: string
      title: getDevicesV3_200_response_inner
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
